"""google oauth states and calendar proposals

Revision ID: ad68b38fe653
Revises: cdf88b5411e1
Create Date: 2026-10-01 06:59:13.445510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad68b38fe653'
down_revision: Union[str, Sequence[str], None] = 'cdf88b5411e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('event_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'created', 'cancelled')", name=op.f('ck_calendar_proposals_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_proposals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_proposals'))
    )
    op.create_index('ix_calendar_proposals_user_id_status', 'calendar_proposals', ['user_id', 'status'], unique=False)
    op.create_table('oauth_states',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nonce', name=op.f('pk_oauth_states'))
    )
    op.create_index('ix_oauth_states_user_id', 'oauth_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_oauth_states_user_id', table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_calendar_proposals_user_id_status', table_name='calendar_proposals')
    op.drop_table('calendar_proposals')
    # ### end Alembic commands ###
